[package]
name = "todo-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.8", features = ["cargo", "derive"] }
serde = "1.0.203"
shlex = "1.3.0"
shell-words = "1.0"